mturkemu/mturk/urls.py
# File: mturk/urls.py
# Author: Carl Allendorph
#
# Description:
#    This file contains the implementation of the urls
# for the worker and requester areas of the site.
#
from django.conf.urls import url

from mturk.worker.views import *

workerPatterns = [
    url('^home/$', WorkerHomePage.as_view(), name="worker-home"),
    # Qualifications
    url('^quals/$', WorkerQualsPage.as_view(), name="worker-quals"),
    url('^quals/(?P<qual_id>[0-9]+)/$', WorkerQualInfoPage.as_view(), name="worker-qual-info"),
    url('^quals/(?P<qual_id>[0-9]+)/request/$', WorkerRequestQual.as_view(), name="worker-qual-request"),
    url('^quals/reqs/$', WorkerQualRequestsPage.as_view()),
    url('^quals/reqs/(?P<req_id>[0-9]+)/test/$', WorkerCompleteQualTest.as_view(), name="worker-qual-test"),
    url('^quals/grants/$', WorkerQualGrantsPage.as_view()),
    # Tasks
    url('^tasks/$', WorkerTasksPage.as_view(), name="worker-tasks"),
    url('^tasks/(?P<task_id>[0-9]+)/$', WorkerTaskInfoPage.as_view(), name="worker-task-info"),
    url('^tasks/(?P<task_id>[0-9]+)/accept/$', WorkerTaskAccept.as_view()),
    url('^tasks/(?P<task_id>[0-9]+)/return/$', WorkerTaskReturn.as_view()),
    url('^tasks/(?P<task_id>[0-9]+)/submit/$', WorkerTaskSubmit.as_view(), name="worker-task-submit"),
    url('^tasks/next/(?P<tasktype_id>[0-9]+)/$', WorkerNextTaskPage.as_view(), name="worker-next-task"),
    url('^tasks/html/$', WorkerHTMLQuestionContent.as_view(), name="worker-html-ques"),

    url('^settings/$', WorkerSettingsPage.as_view(), name="worker-settings"),
]

from mturk.requester.views import *

requesterPatterns = [
    url('^home/$', RequesterHomePage.as_view(), name="requester-home"),

    # Qualification Interface
    url('^quals/$', RequesterQualsPage.as_view(), name="requester-quals"),
    url('^quals/reqs/$', RequesterQualRequestsPage.as_view(), name="requester-qual-requests"),
    url('^quals/reqs/(?P<req_id>[0-9]+)/approve/$', RequesterQualRequestApprove.as_view(), name="requester-qual-request-approve"),
    url('^quals/reqs/(?P<req_id>[0-9]+)/reject/$', RequesterQualRequestReject.as_view(), name="requester-qual-request-reject"),

    url('^quals/grants/$', RequesterQualGrantsPage.as_view(), name="requester-qual-grants"),

    url('^quals/create/$', RequesterQualsCreate.as_view(), name="requester-qual-create"),
    url('^quals/(?P<qual_id>[0-9]+)/$', RequesterQualInfo.as_view()),
    url('^quals/(?P<qual_id>[0-9]+)/remove/$', RequesterQualRemove.as_view()),

    # Tasks Interface
    url('^tasks/$', RequesterTasksPage.as_view(), name="requester-tasks"),
    url('^tasks/(?P<task_id>[0-9]+)/$', RequesterTaskInfoPage.as_view(), name="requester-task-info"),
    url('^tasks/(?P<task_id>[0-9]+)/remove/$', RequesterTaskRemove.as_view(), name="requester-task-remove"),

    url('^tasks/(?P<task_id>[0-9]+)/assign/approve/$', RequesterTaskApproveAll.as_view()),
    url('^tasks/(?P<task_id>[0-9]+)/assign/reject/$', RequesterTaskRejectAll.as_view()),
    url('^tasks/(?P<task_id>[0-9]+)/assign/(?P<assign_id>[0-9]+)/approve/$', RequesterTaskApproveAssignment.as_view()),
    url('^tasks/(?P<task_id>[0-9]+)/assign/(?P<assign_id>[0-9]+)/reject/$', RequesterTaskRejectAssignment.as_view()),


    url('^workers/$', RequesterWorkersPage.as_view()),
    url('^settings/$', RequesterSettingsPage.as_view(), name="requester-settings"),


    # Access Token methods
    url('^access/create/$', RequesterCreateCredential.as_view()),
    url('^access/(?P<cred_id>[0-9]+)/remove/$', RequesterRemoveCredential.as_view()),

]

mturkemu/mturkemu/urls.py
# File: mturkemu/urls.py
# Author: Carl Allendorph
#
# Description:
#   Main URL definitions for the application.
#

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from mturk.views import MTurkMockAPI, MTurkCreateUser
from mturk.worker.views import WorkerExternalSubmit
from mturk.urls import workerPatterns, requesterPatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Default Login/Logout URLs for Django
    url('^accounts/login/', auth_views.login, name="login"),
    url('^accounts/logout/', auth_views.logout, name="logout"),
    url('^accounts/signup/', MTurkCreateUser.as_view(), name="signup"),

    # Main API View -
    # GET = Index Webapp Page
    # POST = MTurk API Endpoint
    url(r'^$', MTurkMockAPI.as_view(), name="index"),
    # UI for the MTurk Emulator
    url(r'^worker/', include(workerPatterns)),
    url(r'^requester/', include(requesterPatterns)),

    # MTurk API Endpoint for ExternalQuestion and HTMLQuestion
    # Objects
    url(r'^mturk/externalSubmit/$', WorkerExternalSubmit.as_view(),
        name="worker-ext-submit"),

]

# In production we need to serve these static images from
# the webserver directly - NOT THROUGH DJANGO
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

mturkemu/mturk/models.py
# File: mturk/models.py
# Author: Carl Allendorph
#
# Description:
#    This file contains the models for the MTurk Emulator.
#

from django.db import models
from django.db.models import Q
from django.core.validators import validate_comma_separated_integer_list
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from mturk.fields import *
from mturk.xml.questions import *
from mturk.xml.quesformanswer import QFormAnswer

from datetime import timedelta
import random
import string

@receiver(post_save, dispatch_uid="aws_id_creation")
def create_aws_id(sender, instance, **kwargs):
    """
    Create the AWS ID for objects that have this field
    This method is called post object save, and will
    cause a second save operation only on creation.
    @note - I think there may be a nicer way to do this with
       a model manager that applies to all objects of a particular
       abstract base type including the AWS ID - but for now
       this works even if it has a slight performance penalty.
    """
    # Applies only to objects with an
    # AWS Id parameter
    try:
        aws_id = instance.aws_id
    except:
        return

    if ( len(aws_id) == 0 ):
        instance.aws_id = CustomerIdField.generate_id(instance)
        instance.save()

class Worker(models.Model):
    """
    Workers implement the tasks created by Requesters
    """
    aws_id = CustomerIdField()
    active = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=False, auto_now_add = True)

    # HIT Statistics

    returned_hits = models.IntegerField(default=0)

    def is_blocked(self, requester):
        """
        Determine if this worker is blocked by the requester
        """
        return(
            self.workerblock_set.filter(
                requester = requester,
                active = True
            ).exists()
        )

    def __str__(self):
        return("<%s, %s...>" % (self.user.username, self.aws_id[0:5]))

class Requester(models.Model):
    """
    Requesters create tasks that are implemented by Workers
    """
    aws_id = CustomerIdField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    MAX_NAME_LEN = 256
    name = models.CharField(max_length = MAX_NAME_LEN, blank=True)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=False, auto_now_add = True)
    balance = models.DecimalField(max_digits=8, decimal_places=2)

    def get_balance(self):
        return("%.02f" % self.balance)

    def __str__(self):
        return("<%s, %s...>" % (self.user.username, self.aws_id[0:5]))

class Credential(models.Model):
    """
    Credentials for a requester to make API requests to the
    server.
    """
    requester = models.ForeignKey(Requester, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    MAX_ACCESS_KEY_LEN = 32
    access_key = models.CharField(max_length=MAX_ACCESS_KEY_LEN)

    MAX_SECRET_KEY_LEN = 64
    secret_key = models.CharField(max_length=MAX_SECRET_KEY_LEN)

    @staticmethod
    def create_random_key(keylen):
        ret = ''.join([
            random.choice(string.ascii_uppercase + string.digits)
            for x in range(0,keylen)
        ])
        return(ret)

class KeywordTag(models.Model):
    """
    Keywords are used to provide easily searchable terms describing
    a qualification or task.
    """
    MAX_VALUE_LEN = 128
    value = models.CharField(max_length=MAX_VALUE_LEN)

    def __str__(self):
        return("<tag=%s>" % self.value)

class KeywordMixinModel(models.Model):
    """
    Abstract base for Models that have a set of keywords
    associated with them.
    """
    class Meta:
        abstract = True

    keywords = models.ManyToManyField(KeywordTag, blank=True)

    def serialize_keywords(self):
        # Convert to a comma separate string of keywords.
        kws = [x.value for x in self.keywords.all()]
        return(",".join(kws))

class SystemQualType(object):
    ######################
    # System Qualification ID Definitions
    ######################
    # Certain Qualifications are defined by the MTurk system
    # and are manages independently from the requesters
    SANDBOX_MASTER = "2ARFPLSP75KLA8M8DH1HTEQVJT3SY6"
    PROD_MASTER = "2F1QJWKUDD8XADTFD2Q0G6UTO95ALH"

    NUM_HITS_APPROVED = "00000000000000000040"
    LOCALE = "00000000000000000071"
    ADULT = "00000000000000000060"

    # @todo - CHECK these system qualification IDs
    #    because they may not be correct
    PERC_APPROVE_RATE = "000000000000000000L0"
    PERC_SUBMIT_RATE = "000000000000000000L1"
    PERC_RETURN_RATE = "000000000000000000L2"
    PERC_REJECT_RATE = "000000000000000000L3"
    PERC_ABANDON_RATE = "000000000000000000L4"
    ######################

class Locale(models.Model):
    """
    Utility class - Strings are ISO 3166 country codes.
    """
    MAX_COUNTRY_LEN = 16
    country = models.CharField(max_length=MAX_COUNTRY_LEN)
    MAX_SUBDIV_LEN = 16
    subdivision = models.CharField(max_length = MAX_SUBDIV_LEN)

    def serialize(self):
        return({
            "Country" : self.country,
            "Subdivision" : self.subdivision
            })

    def __str__(self):
        return("<%s,%s>" % (self.country, self.subdivision))

class Qualification(KeywordMixinModel):
    """
    Qualifications are used to restrict which workers can work
    on what tasks.
    """

    aws_id = CustomerIdField()
    requester = models.ForeignKey(Requester, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=False, auto_now_add = True)

    MAX_NAME_LEN = 256
    name = models.CharField(max_length=MAX_NAME_LEN)
    description=models.TextField()

    # Status of the Qualification - the "Disposing" state is
    # of particular importance but 'Inactive' is also used to
    # disallow workers from requesting
    status = QualStatusField()

    auto_grant = models.BooleanField(default=False)
    auto_grant_value = models.IntegerField(default=1)
    auto_grant_locale = models.ForeignKey(Locale, on_delete=models.PROTECT, null=True)

    requestable = models.BooleanField(default=True)

    retry_active = models.BooleanField(default=False)
    retry_delay = models.DurationField(null=True)

    # We store the text QuestionForm and answer answerKey objects
    # in string format so that they can be read and parsed later when
    # they are needed.
    test = models.TextField(blank=True)
    answer = models.TextField(blank=True)
    test_duration = models.DurationField(null=True)

    # Dispose is a flag indicating that this object needs to
    # be deleted when there are no more outstanding HITs that
    # rely on this qualification.
    dispose = models.BooleanField(default=False)

    def is_active(self):
        return( self.status == QualStatusField.ACTIVE )
    def is_inactive(self):
        return( self.status == QualStatusField.INACTIVE )
    def is_disposing(self):
        return( self.status == QualStatusField.DISPOSING )

    def is_ref_in_active_tasks(self):
        """
        Determine is this qualification is referenced from
        Active Tasks.
        """
        taskTypes = TaskType.objects.filter(
            qualifications__qualification = self
            )

        if ( taskTypes.exists() ):
            activeTasks = Task.objects.filter(
                tasktype__pk__in = taskTypes.values_list("pk", flat=True),
                dispose=False
            )
            return( activeTasks.exists(), taskTypes )

        return(False, taskTypes)

    def purge_grants(self):
        """
        This qualification is being disposed of - so we need to remove
        any active grants
        """

        grants = QualificationGrant.objects.filter(
            qualification = self,
            dispose=False
            )
        for grant in grants:
            grant.dispose = True
            grant.save()



    @property
    def has_test(self):
        return( len(self.test) > 0 )

    @property
    def total_grants(self):
        ret = QualificationGrant.objects.filter(
            qualification = self,
            active = True
            ).count()
        return(ret)

    def serialize(self):
        ret = {
            "QualificationTypeId" : self.aws_id,
            "CreationTime" : self.created,
            "Name" : self.name,
            "Description" : self.description,
            "Keywords" : self.serialize_keywords(),
            "QualificationTypeStatus" : self.get_status_display(),
            "IsRequestable" : self.requestable,
            "AutoGranted" : self.auto_grant,
        }
        if ( len(self.test) > 0):
            ret["Test"] = self.test
            ret["TestDurationInSeconds"] = int(self.test_duration.total_seconds())
        if ( len(self.answer) > 0):
            ret["AnswerKey"] = self.answer

        if ( self.auto_grant ):
            ret["AutoGrantedValue"] = self.auto_grant_value
        if ( self.retry_active ):
            ret["RetryDelayInSeconds"] = int(self.retry_delay.total_seconds())

        return(ret)

    def __str__(self):
        return("<%s...>" % self.aws_id[0:6])

class QualificationRequest(models.Model):
    """
    Qualification Requests are created when a worker makes a
    request to receive a particular qualification.
    """
    aws_id = CustomerIdField()
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    qualification = models.ForeignKey(Qualification, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=False, auto_now_add = True)

    last_request = models.DateTimeField()

    # The state of this request - indicates what actions the
    # worker/requester has completed in relation to this request.
    state = QualReqStatusField()

    # Answer contains the response data from the Worker when they

mturkemu/mturk/forms.py
# File: mturk/forms.py
# Author: Carl Allendorph
#
# Description:
#   This file contains the implementation of the forms for the
# mturk app

from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from mturk.models import *

def check_user_exists(value):
    if ( User.objects.filter(username = value).exists() ):
        raise ValidationError("User with username[%s] already Exists!" % value)


class UserSignupForm(forms.Form):
    """
    Form for creating a new user
    """
    username = forms.CharField(max_length=150, label="Username", validators=[check_user_exists])
    email = forms.EmailField(required=False, label="Email")
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

class QueryForm(forms.Form):
    """
    This form is for providing a search query for a list
    """
    MAX_QUERY_LEN = 256
    query = forms.CharField(max_length = MAX_QUERY_LEN, label="Query", required=False)

class ListViewForm(forms.Form):
    """
    This form is for allowing lists to be paginated in a template
    """
    offset = forms.IntegerField(min_value=1, required=False)
    count = forms.IntegerField(min_value=1, required=False)

class QualCreateForm(forms.Form):
    """
    This form is for allowing the requester to  make a basic qualification
    through the web interface
    """

    name = forms.CharField(max_length = Qualification.MAX_NAME_LEN, label="Name")
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'rows': 4}))


class ExternalQuestionForm(forms.Form):
    """
    This form is used as GET encoded arguments to the
    ExternalQuestion or the HTMLQuestion objects.
    """
    assignmentId = forms.CharField(max_length = 256 )
    workerId = forms.CharField(max_length = 256)
    hitId = forms.CharField(max_length = 256)
    turkSubmitTo = forms.URLField(max_length=512)

mturkemu/mturk/templates/requester/access_token_panel.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> API Access Tokens </h3>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Access Key</th>
          <th>Secret Key</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for access in access_list %}
        <tr>
          <td> {{access.access_key}} </td>
          <td> {{access.secret_key}} </td>
          <td>
            <a class="btn btn-default" href="/requester/access/{{access.id}}/remove/">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="3">
            No Access Tokens Available.
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class="btn" href="/requester/access/create/">
      Create Access Token
    </a>
  </div>
</div>

mturkemu/mturk/templates/requester/grant_table.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> Grants </h3>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th> Worker </th>
          <th> Qualification </th>
          <th> Granted On </th>
          <th> Actions </th>
        </tr>
      </thead>
      <tbody>
        {% for grant in grants.list %}
        <tr>
          <td> {{grant.worker.aws_id}} </td>
          <td> {{grant.qualification.name}} </td>
          <td> {{grant.granted}} </td>
          <td>
            {% if grant.active %}
            <a class="btn btn-default" href="/requester/quals/grants/{{grant.id}}/revoke/">
              <span class="glyphicon glyphicon-trash"/>
            </a>
            {% else %}
            <a class="btn btn-default" href="/requester/quals/grants/{{grant.id}}/approve/">
              <span class="glyphicon glyphicon-plus"/>
            </a>
            {% endif %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="4"> No Grants Present </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
  <div class="panel-footer">
    {% include "comps/pager.html" with url="/requester/quals/grants/" page=grants %}
  </div>
</div>

mturkemu/mturk/templates/requester/home.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Requester Dashboard</h2>
    {% include "requester/requester_id.html" with requester=requester %}

  </div>
</div>
{% endblock %}

mturkemu/mturk/templates/requester/qual_create.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
{% load bootstrap3 %}

<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Create Qualification </h2>
    <ol class="breadcrumb">
      <li>Id: {{ requester.aws_id }}</li>
    </ol>

    <div class="panel panel-default">
      <div class="panel-body">
        <p>
          Create a simple qualification below. The name must
          be unique for your account. This new qualification
          will not auto grant, which means workers can request
          it but you will have to manually approve the requests.
          For more control over qualifications, use the MTurk API to
          create a qualification.
        </p>

        <form method="POST" action="{% url 'requester-qual-create' %}">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% buttons %}
          <button type="submit" class="btn btn-primary">
            Create
          </button>
          {% endbuttons %}
        </form>
      </div>
    </div>

  </div>
</div>
{% endblock %}

mturkemu/mturk/templates/requester/qual_info.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Requester Qualification</h2>
    {% include "requester/requester_id.html" with requester=requester %}

    {% include "requester/qual_info_table.html" with qual=qual %}
  </div>
</div>
{% endblock %}

mturkemu/mturk/templates/requester/qual_info_table.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> Qualification </h3>
  </div>
  <div class="panel-body">

    <table class="table">
      <thead>
        <tr>
          <th> Property </th>
          <th> Value </th>
        </tr>
      </thead>
      <tbody>
        {% for info in qual_info %}
        <tr>
          <td> {{info.label}} </td>
          <td> {{info.value}} </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="2"> ERROR: No Qual Info Present </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

mturkemu/mturk/templates/requester/qual_requests.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Qualification Requests </h2>
    {% include "requester/requester_id.html" with requester=requester %}

    {% include "requester/req_table.html" with requests=requests %}

  </div>
</div>
{% endblock %}

mturkemu/mturk/templates/requester/quals.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Requester Qualifications</h2>
    {% include "requester/requester_id.html" with requester=requester %}

    {% include "requester/qual_table.html" with quals=quals %}
  </div>
</div>
{% endblock %}

mturkemu/mturk/templates/requester/requester_id.html
<ol class="breadcrumb">
  <li>Requester: {{ requester.aws_id }}</li>
</ol>

mturkemu/mturk/templates/requester/root.html
{% extends "root.html" %}

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2">
      {% block sidebar %}
      {% endblock %}
    </div>
    <div class="col-sm-9 col-md-10">
      {% block tab %}
      {% endblock %}
    </div>
  </div>
</div>

{% endblock %}

mturkemu/mturk/templates/requester/sidebar.html
<div class="list-group">
  <a class="list-group-item {% if active == 'home' %}active{% endif %}"
     href="/requester/home/"> Home </a>
  <a class="list-group-item {% if active == 'quals' %}active{% endif %}"
     href="/requester/quals/">
    Qualifications
  </a>
  {% if active == "quals" %}
  <a class="list-group-item" href="/requester/quals/reqs/">
    <div class="list-group-child">
      Pending Requests
    </div>
  </a>
  <a class="list-group-item" href="/requester/quals/grants/">
    <div class="list-group-child">
      Worker Grants
    </div>
  </a>
  {% endif %}
  <a class="list-group-item {% if active == 'tasks' %}active{% endif %}"
     href="/requester/tasks/"> Tasks </a>
  <a class="list-group-item {% if active == 'workers' %}active{% endif %}"
     href="/requester/workers/"> Workers </a>
  <a class="list-group-item  {% if active == 'settings' %}active{% endif %}"
     href="/requester/settings/"> Settings </a>
</div>

mturkemu/mturk/templates/requester/task_info.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Requester Tasks</h2>
    {% include "requester/requester_id.html" with requester=requester %}
    {% include "comps/server_msgs.html" %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h2> Task: {{task.tasktype.title}} </h2>
  </div>
  <div class="panel-body">
    {#  I want to show info about this particular task to include qualifications and other such information  #}
    <h3> Properties </h3>
    {% include "comps/property_table.html" with props=task.prop_table %}

    <h3> Qualifications </h3>
    {% include "comps/qualreq_table.html" with qualreqs=task.tasktype.qualifications.all %}
    <h3> Actions </h3>
    <ul>
      <li>
        <a href="/requester/tasks/{{task.id}}/remove/"> Delete Task </a>
      </li>
    </ul>

  </div>
</div>

{% include "requester/submitted_assignments.html" with task=task %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h2> Completed Assignments </h2>
  </div>

  <div clas="panel-body">
    <p>
      These assignmnents have been completed with a decision
      to approve or reject.
    </p>

    {% for assignment in task.completed_assignments %}
    {% if assignment.is_approved %}
    <div class="panel panel-success" style="margin: 20px">
    {% elif assignment.is_rejected %}
    <div class="panel panel-danger" style="margin: 20px">
    {% else %}
    <div class="panel panel-warning" style="margin: 20px">
    {% endif %}
      <div class="panel-heading">
        <h3> Assignment: {{assignment.aws_id}} </h3>
      </div>
      <div class="panel-body">
        <h4> Assignment Parameters </h4>
        {% include "comps/property_table.html" with props=assignment.prop_table %}
        <h4> Answers </h4>
        {% include "comps/qformanswer_table.html" with answers=assignment.get_answer_display %}
      </div>

    </div>
    {% empty %}
    <div class="well" style="margin:20px">
      No Completed Assignments are Present
    </div>
    {% endfor %}
  </div>
</div>

    {% endblock %}

mturkemu/mturk/templates/requester/task_table.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3> Tasks </h3>
  </div>
  <div class="panel-body">

    <table class="table table-hover">
      <thead>
        <tr>
          <th rowspan="2"> Title </th>
          <th rowspan="2"> Status </th>
          <th rowspan="1" colspan="4"> Assignments </th>
          <th rowspan="2"> Expires </th>
        </tr>
        <tr>
          <th>Available</th>
          <th>Pending</th>
          <th>Completed</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks.list %}
        {% with stats=task.compute_assignment_stats %}
        <tr onclick="window.document.location='/requester/tasks/{{task.id}}/';">
          <td> {{task.tasktype.title}} </td>
          <td> {{task.get_status_display}} </td>
          <td> {{stats.0}} </td>
          <td> {{stats.1}} </td>
          <td> {{stats.2}} </td>
          <td> {{task.max_assignments}} </td>
          <td> {{task.expires}} </td>
        </tr>
        {% endwith %}
        {% empty %}
        <tr>
          <td colspan="7"> No Tasks Present </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
  <div class="panel-footer">
    {% include "comps/pager.html" with url="/requester/tasks/" page=tasks %}
  </div>
</div>

mturkemu/mturk/templates/requester/tasks.html
{% extends "requester/root.html" %}

{% block sidebar %}
{% include "requester/sidebar.html" %}
{% endblock %}

{% block tab %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2> Requester Tasks</h2>
    {% include "requester/requester_id.html" with requester=requester %}
    {% include "comps/server_msgs.html" %}

    {% include "requester/task_table.html" with tasks=tasks %}
  </div>
</div>
{% endblock %}